# Generated by Django 2.1.5 on 2019-01-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
