# Generated by Django 2.1.5 on 2019-01-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0002_auto_20190114_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
