# Generated by Django 2.1.5 on 2019-01-17 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0005_orderinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinformation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
