# Generated by Django 2.1.5 on 2019-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0006_auto_20190117_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinformation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderinformation',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='OrderInformation',
        ),
    ]
