# Generated by Django 2.1.5 on 2019-01-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0007_auto_20190117_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
