# Generated by Django 2.1.5 on 2019-01-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0008_auto_20190118_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_numbers',
            field=models.CharField(default='', max_length=16),
        ),
    ]
