# Generated by Django 2.1.5 on 2019-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0009_userprofile_phone_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='telephone_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
