# Generated by Django 2.1.5 on 2019-01-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0010_auto_20190120_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookstore.Category'),
        ),
    ]
