# Generated by Django 2.1.5 on 2019-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0011_stores_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='Store_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
