# Generated by Django 2.1.5 on 2019-01-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0014_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='complain',
            name='telephone_number',
            field=models.CharField(default='', max_length=16),
        ),
    ]
