# Generated by Django 2.1.5 on 2019-01-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0020_saleontelestai'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookstore.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'started'), ('Seen', 'seen'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='started', max_length=120),
        ),
    ]
