# Generated by Django 2.1.5 on 2019-01-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebookstore', '0023_auto_20190130_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
