# Generated by Django 2.1.5 on 2019-01-30 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebookstore', '0028_auto_20190130_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='store',
        ),
        migrations.AddField(
            model_name='variation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
